# Generated by Django 5.0.14 on 2025-04-17 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mahsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('chaxlash', models.BooleanField(default=False)),
                ('lazer', models.BooleanField(default=False)),
                ('default_amount', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Mijoz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('color', models.CharField(default='#fff', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Jarayon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('order', models.PositiveIntegerField(help_text='Controls global ordering if you ever list them in the app.')),
                ('can_edit', models.ManyToManyField(related_name='jarayon_edit', to='auth.group')),
                ('can_view', models.ManyToManyField(related_name='jarayon_view', to='auth.group')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MahsulotJarayon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('jarayon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.jarayon')),
                ('mahsulot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.mahsulot')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('mahsulot', 'jarayon')},
            },
        ),
        migrations.AddField(
            model_name='mahsulot',
            name='jarayonlar',
            field=models.ManyToManyField(through='production.MahsulotJarayon', to='production.jarayon'),
        ),
        migrations.AddField(
            model_name='mahsulot',
            name='padosh_colors',
            field=models.ManyToManyField(related_name='padoshable_products', to='production.rang'),
        ),
        migrations.AddField(
            model_name='mahsulot',
            name='rand_colors',
            field=models.ManyToManyField(blank=True, related_name='randable_products', to='production.rang'),
        ),
        migrations.AddField(
            model_name='mahsulot',
            name='style_colors',
            field=models.ManyToManyField(blank=True, related_name='stylable_products', to='production.rang'),
        ),
        migrations.CreateModel(
            name='Zakaz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('finished', models.DateField(blank=True, null=True)),
                ('partial', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Yangi', 'Yangi'), ('Qisman Sotildi', 'Qisman Sotildi'), ('Sotildi', 'Sotildi'), ('Otmen', 'Otmen')], default='Yangi', max_length=20)),
                ('quantity', models.PositiveIntegerField()),
                ('use_lazer', models.BooleanField(default=False)),
                ('use_chaxlash', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.mijoz')),
                ('padosh_color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='zakaz_padosh', to='production.rang')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.mahsulot')),
                ('rand_color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='zakaz_rand', to='production.rang')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to=settings.AUTH_USER_MODEL)),
                ('style_color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='zakaz_style', to='production.rang')),
            ],
        ),
        migrations.CreateModel(
            name='Sotuv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sold_date', models.DateField(auto_now_add=True)),
                ('quantity', models.PositiveIntegerField()),
                ('approved', models.BooleanField(default=False)),
                ('approved_date', models.DateField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.zakaz')),
            ],
        ),
        migrations.CreateModel(
            name='ZakazProizvodstvo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Yangi', 'Yangi'), ('Bajarilmoqda', 'Bajarilmoqda'), ('Bajarildi', 'Bajarildi')], default='Yangi', max_length=20)),
                ('created', models.DateField()),
                ('started', models.DateField(blank=True, null=True)),
                ('finished', models.DateField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField()),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='production.zakaz')),
            ],
        ),
        migrations.CreateModel(
            name='Sklad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chaxlash', models.BooleanField(default=False)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('padosh_color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sklad_padosh', to='production.rang')),
                ('produkt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.mahsulot')),
                ('rand_color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sklad_rand', to='production.rang')),
                ('style_color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sklad_style', to='production.rang')),
            ],
            options={
                'unique_together': {('produkt', 'style_color', 'padosh_color', 'rand_color', 'chaxlash')},
            },
        ),
        migrations.CreateModel(
            name='Proizvodstvo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('brak', models.PositiveIntegerField(default=0)),
                ('total_brak', models.PositiveIntegerField(default=0)),
                ('jarayon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.jarayon')),
                ('zp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.zakazproizvodstvo')),
            ],
            options={
                'unique_together': {('zp', 'jarayon')},
            },
        ),
    ]
