# Generated by Django 5.0.14 on 2025-04-18 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mahsulot',
            name='jarayonlar',
        ),
        migrations.AlterModelOptions(
            name='jarayon',
            options={'ordering': ['order'], 'verbose_name': 'Jarayon', 'verbose_name_plural': 'Jarayonlar'},
        ),
        migrations.AlterModelOptions(
            name='mahsulot',
            options={'verbose_name': 'Mahsulot', 'verbose_name_plural': 'Mahsulotlar'},
        ),
        migrations.AlterModelOptions(
            name='mijoz',
            options={'verbose_name': 'Mijoz', 'verbose_name_plural': 'Mijozlar'},
        ),
        migrations.AlterModelOptions(
            name='proizvodstvo',
            options={'verbose_name': 'Proizvodstvo', 'verbose_name_plural': 'Proizvodstvo'},
        ),
        migrations.AlterModelOptions(
            name='rang',
            options={'verbose_name': 'Rang', 'verbose_name_plural': 'Ranglar'},
        ),
        migrations.AlterModelOptions(
            name='sklad',
            options={'verbose_name': 'Sklad', 'verbose_name_plural': 'Sklad'},
        ),
        migrations.AlterModelOptions(
            name='sotuv',
            options={'verbose_name': 'Sotuv', 'verbose_name_plural': 'Sotuvlar'},
        ),
        migrations.AlterModelOptions(
            name='zakaz',
            options={'verbose_name': 'Zakaz', 'verbose_name_plural': 'Zakazlar'},
        ),
        migrations.AlterModelOptions(
            name='zakazproizvodstvo',
            options={'verbose_name': 'Zakaz Proizvodstvo', 'verbose_name_plural': 'Zakaz Proizvodstvo'},
        ),
        migrations.DeleteModel(
            name='MahsulotJarayon',
        ),
    ]
