# Generated by Django 5.0.14 on 2025-04-18 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_remove_mahsulot_jarayonlar_alter_jarayon_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahsulot',
            name='jarayonlar',
            field=models.ManyToManyField(related_name='mahsulotlar', to='production.jarayon'),
        ),
    ]
