# Generated by Django 5.0.14 on 2025-04-18 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_mahsulot_jarayonlar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahsulot',
            name='jarayonlar',
            field=models.ManyToManyField(blank=True, related_name='mahsulotlar', to='production.jarayon'),
        ),
    ]
