# Generated by Django 5.0.14 on 2025-04-25 11:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_alter_mahsulot_jarayonlar'),
    ]

    operations = [
        migrations.AddField(
            model_name='mijoz',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mijoz',
            name='phone',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='zakaz',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
