# Generated by Django 5.0.14 on 2025-04-26 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0005_mijoz_created_mijoz_phone_zakaz_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='proizvodstvo',
            name='finished',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proizvodstvo',
            name='started',
            field=models.DateField(blank=True, null=True),
        ),
    ]
