# Generated by Django 5.0.14 on 2025-04-29 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0006_proizvodstvo_finished_proizvodstvo_started'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sotuv',
            name='sold_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
