# Generated by Django 5.0.14 on 2025-04-29 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0007_alter_sotuv_sold_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sotuv',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='production.zakaz'),
        ),
    ]
