# Generated by Django 5.0.14 on 2025-04-29 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0008_alter_sotuv_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sotuv',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.zakaz'),
        ),
    ]
